import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container-fluid">
      <Head>
        <title>Penina Berkowitz SovTech Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-light m-3 bg-light">
        <div className="container-fluid">
          <a className="navbar-brand" href="#">
            Penina Berkowitz SovTech Challenge
          </a>
        </div>
      </nav>

      <hr className="featurette-divider"></hr>

      <div className="row justify-content-start featurette m-5 p-3 bg-primary align-items-center justify-content-between">
        <div className="col-9 p-2">
          <h2 className="featurette-heading fw-normal lh-1 text-start">
            About Me{" "}   
          </h2>
          <h2> 
            <span className="text-muted text-start">Coding Experience</span>
          </h2>
          <p className="lead text-start">
           - I fell in love with coding when I was in grade 10 and took IT as a subject. <br></br>
           - By the end of Grade 11, my IT teacher insisted that I study for a degree that involves coding.<br></br> 
           - I attended to Varsity College where I completed first and second year in one year. <br></br>
           - I graduated from Varsity College with distinction, my degree being in Computer and Information Sciences with Application Development. <br></br>
           - I continued my studies at the University of Johannesburg with a post graduate Honours Degree being a BSc Computer Science. <br></br>
           - Whilst I do have a preference for backend development over frontend creation my creative side does assist me with the latter 
           and I am therefore well suited to both. I also see myself as an asset to an organisation, as being skilled in both, enables me to work up either of, 
           or both ends of initial conceptual frameworks that can then later be fully developed and refined to a finished product by a team.
          </p>
        </div>
        <div className="col-3">
        <div>
                <Image
                    src="/laptop.png"
                    alt="GFG logo served with static path of public directory"
                    height="250"
                    width="300"
                />
            </div>
        </div>
      </div>

      {/* <hr className="featurette-divider"></hr> */}

      <div className="row justify-content-end featurette m-5 p-3 bg-info align-items-center">
      <div className="col-9 order-md-2">
        <h2 className="featurette-heading fw-normal lh-1 ">About Me </h2>
        <h2 className=""><span className="text-muted ">Hobbies</span></h2>
        <p className="lead ">
          I am a creative person and I express my creativity through my hobbies. <br></br>
          I am a photographer. I love both shooting images and editing them. I have toyed in fine art photography 
          and once was an award winner and have also done people and family photography as a business side-line. <br></br>
          I also sew; my mother taught me how to sew during lockdown and now have fun experimenting and creating 
          clothes for myself and my sisters.<br></br><br></br>
          Another thing I am passionate about is constantly bettering myself. <br></br>
          I attend gym at least 5 times a week which boosts me both physically and 
          Mentally. My gym “buddies” are all positive people and together we create positive memories.
        </p>
      </div>
      <div className="col-3 order-md-1">
        <Image
          src="/camera.png"
          alt="GFG logo served with static path of public directory"
          height="150"
          width="200"
        />
      </div> 
    </div>
    <hr className="featurette-divider"></hr>

    <div className="row justify-content-start featurette m-5 p-3 bg-secondary align-items-center justify-content-between">
        <div className="col-9 p-2">
          <h2 className="featurette-heading fw-normal lh-1 text-start">
            SovTech{" "}   
          </h2>
          <h2> 
            <span className="text-muted text-start">Why I Want to Be A Developer</span>
          </h2>
          <p className="lead text-start">
            When seeking a working environment, my ideal would be company where I will acquire new skills and grow 
            professionally in an environment that exudes a good community spirit and a positive energy. <br></br>
            Based on what I have read and heard about Sovtech, I believe that it is precisely what I have been looking for. <br></br>
            I want to be surrounded by and work together with good people whom I can learn from and who can learn from me.
          </p>
        </div>
        <div className="col-3">
        <div>
                <Image
                    src="/sovtech-logo.png"
                    alt="GFG logo served with static path of public directory"
                    height="200"
                    width="200"
                />
            </div>
        </div>
      </div>

      <hr className="featurette-divider"></hr>
    </div>
  );
}
